import type { IApplication } from "../models/Application.js";

function daysFromNow(days: number, hour = 10, minute = 0): Date {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  date.setDate(date.getDate() + days);
  return date;
}

function dateInNextMonth(day: number, hour = 10, minute = 0): Date {
  const date = new Date();
  date.setDate(1);
  date.setMonth(date.getMonth() + 1);
  date.setDate(day);
  date.setHours(hour, minute, 0, 0);
  return date;
}

function daysAgo(days: number): Date {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(9, 0, 0, 0);
  return date;
}

export function createDemoApplications(userId: IApplication["userId"]) {
  return [
    {
      userId,
      company: "Northstar Labs",
      position: "Frontend Engineer",
      location: "Berlin, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "interview",
      technologies: ["React", "TypeScript", "TanStack Query"],
      jobDescription: "Build accessible React interfaces with TypeScript, collaborate with product and design, and connect features to REST APIs.",
      appliedAt: daysAgo(18),
      interviewDate: daysFromNow(2, 10, 30),
      notes: "Second-round interview with the product engineering team.",
      createdAt: daysAgo(19),
      updatedAt: daysAgo(2),
    },
    {
      userId,
      company: "Cloudforge",
      position: "Full Stack Developer",
      location: "Hamburg, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "technical_interview",
      technologies: ["React", "Node.js", "MongoDB"],
      jobDescription: "Develop responsive React features and Node.js APIs, work with MongoDB data, and improve automated test coverage.",
      appliedAt: daysAgo(22),
      interviewDate: dateInNextMonth(8, 14, 0),
      notes: "Technical discussion focused on APIs and frontend architecture.",
      createdAt: daysAgo(24),
      updatedAt: daysAgo(3),
    },
    {
      userId,
      company: "OrbitWorks",
      position: "Web Application Developer",
      location: "Munich, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "screening",
      technologies: ["Vue", "TypeScript", "REST"],
      appliedAt: daysAgo(9),
      notes: "Recruiter screening completed; waiting for engineering feedback.",
      createdAt: daysAgo(11),
      updatedAt: daysAgo(1),
    },
    {
      userId,
      company: "BrightPixel",
      position: "Senior Frontend Developer",
      location: "Frankfurt, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "applied",
      technologies: ["React", "Accessibility", "Cypress"],
      appliedAt: daysAgo(4),
      createdAt: daysAgo(5),
      updatedAt: daysAgo(4),
    },
    {
      userId,
      company: "Nexora Systems",
      position: "Frontend Developer",
      location: "Cologne, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "offer",
      technologies: ["React", "TypeScript", "GraphQL"],
      appliedAt: daysAgo(31),
      notes: "Offer received. Reviewing compensation and start date.",
      createdAt: daysAgo(34),
      updatedAt: daysAgo(1),
    },
    {
      userId,
      company: "PixelRoute",
      position: "React Developer",
      location: "Stuttgart, Germany",
      workplaceType: "onsite",
      employmentType: "full_time",
      status: "rejected",
      technologies: ["React", "JavaScript", "Jest"],
      appliedAt: daysAgo(44),
      createdAt: daysAgo(47),
      updatedAt: daysAgo(20),
    },
    {
      userId,
      company: "GreenStack",
      position: "Full Stack JavaScript Developer",
      location: "Freiburg, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "saved",
      technologies: ["React", "Node.js", "PostgreSQL"],
      notes: "Interesting role. Review the job description before applying.",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      userId,
      company: "DataNest",
      position: "Frontend Engineer",
      location: "Remote, Germany",
      workplaceType: "remote",
      employmentType: "contract",
      status: "withdrawn",
      technologies: ["TypeScript", "React", "Design Systems"],
      appliedAt: daysAgo(67),
      createdAt: daysAgo(70),
      updatedAt: daysAgo(51),
    },
    {
      userId,
      company: "Studio Meridian",
      position: "UI Engineer",
      location: "Düsseldorf, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "applied",
      technologies: ["React", "CSS", "Storybook"],
      appliedAt: daysAgo(13),
      createdAt: daysAgo(14),
      updatedAt: daysAgo(13),
    },
    {
      userId,
      company: "Vector One",
      position: "Software Developer",
      location: "Karlsruhe, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "screening",
      technologies: ["TypeScript", "Node.js", "Docker"],
      appliedAt: daysAgo(82),
      createdAt: daysAgo(84),
      updatedAt: daysAgo(60),
    },
    {
      userId,
      company: "Pinecone Digital",
      position: "Frontend Software Engineer",
      location: "Leipzig, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "rejected",
      technologies: ["React", "TypeScript", "Testing Library"],
      appliedAt: daysAgo(105),
      createdAt: daysAgo(108),
      updatedAt: daysAgo(91),
    },
    {
      userId,
      company: "Helio Commerce",
      position: "E-commerce Frontend Developer",
      location: "Nuremberg, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "withdrawn",
      technologies: ["JavaScript", "React", "REST"],
      appliedAt: daysAgo(132),
      createdAt: daysAgo(135),
      updatedAt: daysAgo(120),
    },
    {
      userId,
      company: "AsterGrid",
      position: "Product Frontend Developer",
      location: "Berlin, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "saved",
      technologies: ["React", "TypeScript", "Vite"],
      notes: "Review the team and product before applying.",
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
    {
      userId,
      company: "Clearbrook Systems",
      position: "TypeScript Engineer",
      location: "Bonn, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "applied",
      technologies: ["TypeScript", "React", "GraphQL"],
      appliedAt: daysAgo(6),
      createdAt: daysAgo(7),
      updatedAt: daysAgo(6),
    },
    {
      userId,
      company: "Slate & Birch",
      position: "Design Systems Engineer",
      location: "Dresden, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "screening",
      technologies: ["React", "Accessibility", "Storybook"],
      appliedAt: daysAgo(10),
      notes: "Portfolio shared with the design team.",
      createdAt: daysAgo(12),
      updatedAt: daysAgo(3),
    },
    {
      userId,
      company: "Wavefront Health",
      position: "UX Engineer",
      location: "Heidelberg, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "interview",
      technologies: ["Vue", "TypeScript", "CSS"],
      jobDescription: "Build accessible patient-facing interfaces, collaborate with designers, and maintain a reusable component library.",
      appliedAt: daysAgo(15),
      interviewDate: daysFromNow(5, 11, 0),
      notes: "Prepare examples of accessible form design.",
      createdAt: daysAgo(16),
      updatedAt: daysAgo(2),
    },
    {
      userId,
      company: "Harborline Cloud",
      position: "API Integration Developer",
      location: "Bremen, Germany",
      workplaceType: "remote",
      employmentType: "contract",
      status: "applied",
      technologies: ["Node.js", "REST", "Docker"],
      appliedAt: daysAgo(19),
      createdAt: daysAgo(20),
      updatedAt: daysAgo(19),
    },
    {
      userId,
      company: "Comet Retail",
      position: "Full Stack Engineer",
      location: "Dortmund, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "technical_interview",
      technologies: ["React", "Node.js", "MongoDB"],
      jobDescription: "Deliver storefront features and Express APIs, with automated tests for the checkout journey.",
      appliedAt: daysAgo(25),
      interviewDate: daysFromNow(9, 15, 0),
      notes: "Practice API design and testing questions.",
      createdAt: daysAgo(27),
      updatedAt: daysAgo(4),
    },
    {
      userId,
      company: "Atlas Mobility",
      position: "UI Platform Developer",
      location: "Hannover, Germany",
      workplaceType: "onsite",
      employmentType: "full_time",
      status: "screening",
      technologies: ["Angular", "RxJS", "TypeScript"],
      appliedAt: daysAgo(29),
      createdAt: daysAgo(30),
      updatedAt: daysAgo(8),
    },
    {
      userId,
      company: "Blueleaf Energy",
      position: "Angular Developer",
      location: "Essen, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "offer",
      technologies: ["Angular", "NgRx", "REST"],
      appliedAt: daysAgo(37),
      notes: "Compare the offer with other active opportunities.",
      createdAt: daysAgo(38),
      updatedAt: daysAgo(2),
    },
    {
      userId,
      company: "Copperfield Labs",
      position: "Junior Software Engineer",
      location: "Mannheim, Germany",
      workplaceType: "onsite",
      employmentType: "full_time",
      status: "rejected",
      technologies: ["JavaScript", "React", "Jest"],
      appliedAt: daysAgo(41),
      createdAt: daysAgo(42),
      updatedAt: daysAgo(12),
    },
    {
      userId,
      company: "Morrow Finance",
      position: "Frontend Platform Engineer",
      location: "Berlin, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "applied",
      technologies: ["Vue", "TypeScript", "Vitest"],
      appliedAt: daysAgo(51),
      createdAt: daysAgo(52),
      updatedAt: daysAgo(51),
    },
    {
      userId,
      company: "OpenTrail Media",
      position: "Web Accessibility Engineer",
      location: "Remote, Germany",
      workplaceType: "remote",
      employmentType: "part_time",
      status: "saved",
      technologies: ["HTML", "WCAG", "React"],
      notes: "Check whether the part-time hours fit the schedule.",
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
    {
      userId,
      company: "SilverOak Analytics",
      position: "Dashboard Developer",
      location: "Mainz, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "screening",
      technologies: ["React", "Charts", "TypeScript"],
      appliedAt: daysAgo(71),
      createdAt: daysAgo(72),
      updatedAt: daysAgo(38),
    },
    {
      userId,
      company: "VistaWorks",
      position: "Frontend Consultant",
      location: "Remote, Germany",
      workplaceType: "remote",
      employmentType: "freelance",
      status: "withdrawn",
      technologies: ["React", "CSS", "Accessibility"],
      appliedAt: daysAgo(89),
      createdAt: daysAgo(90),
      updatedAt: daysAgo(62),
    },
    {
      userId,
      company: "Ember Product",
      position: "React Engineer",
      location: "Potsdam, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "interview",
      technologies: ["React", "TanStack Query", "Testing Library"],
      appliedAt: daysAgo(96),
      interviewDate: daysFromNow(14, 9, 30),
      notes: "Review past projects and prepare questions for the team.",
      createdAt: daysAgo(97),
      updatedAt: daysAgo(1),
    },
    {
      userId,
      company: "Lumen Studio",
      position: "Interface Engineer",
      location: "Kiel, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "applied",
      technologies: ["CSS", "Vue", "Storybook"],
      appliedAt: daysAgo(114),
      createdAt: daysAgo(115),
      updatedAt: daysAgo(114),
    },
    {
      userId,
      company: "PrismBridge",
      position: "Developer Experience Engineer",
      location: "Aachen, Germany",
      workplaceType: "remote",
      employmentType: "full_time",
      status: "rejected",
      technologies: ["TypeScript", "Node.js", "CI/CD"],
      appliedAt: daysAgo(123),
      createdAt: daysAgo(124),
      updatedAt: daysAgo(80),
    },
    {
      userId,
      company: "Meadowline Commerce",
      position: "UI Developer",
      location: "Ulm, Germany",
      workplaceType: "hybrid",
      employmentType: "full_time",
      status: "applied",
      technologies: ["React", "JavaScript", "REST"],
      appliedAt: daysAgo(139),
      createdAt: daysAgo(140),
      updatedAt: daysAgo(139),
    },
    {
      userId,
      company: "Northwind Mobility",
      position: "Software Engineer",
      location: "Regensburg, Germany",
      workplaceType: "onsite",
      employmentType: "internship",
      status: "saved",
      technologies: ["TypeScript", "Angular", "Git"],
      createdAt: daysAgo(160),
      updatedAt: daysAgo(160),
    },
  ];
}
